{ config, pkgs, lib, ... }:
let
  # Shared MCP server definitions (also used by Claude Code)
  mcpServers = import ./mcp-servers.nix;

  # Skills that need to be copied (same as Claude Code)
  skillsToCopy = {
    generate-smithy = ./ai/skills/generate-smithy;
    api-to-proto    = ./ai/skills/api-to-proto;
    bootstrap-rust  = ./ai/skills/bootstrap-rust;
    tdd             = ./ai/skills/tdd;
  };

  # Agents (shared with Claude Code)
  agentsToCopy = {
    codebase-analyzer       = ./ai/agents/codebase-analyzer.md;
    codebase-locator        = ./ai/agents/codebase-locator.md;
    codebase-pattern-finder = ./ai/agents/codebase-pattern-finder.md;
    thoughts-analyzer       = ./ai/agents/thoughts-analyzer.md;
    thoughts-locator        = ./ai/agents/thoughts-locator.md;
    web-search-researcher   = ./ai/agents/web-search-researcher.md;
  };

  # Commands (shared with Claude Code)
  commandsToCopy = {
    commit     = ./ai/commands/commit.md;
    create-rfc = ./ai/commands/create_rfc.md;
  };

  # Convert MCP servers from our shared format to Codex TOML format
  # Codex uses:
  #   - stdio: command, args, env (as sub-table)
  #   - http: url, bearer_token_env_var
  mcpServerToToml = name: server:
    if server ? type && server.type == "sse" then
      # SSE/HTTP server
      ''
        [mcp_servers.${name}]
        url = "${server.url}"
      ''
    else
      # stdio server (command + args)
      let
        argsStr = lib.concatMapStringsSep ", " (a: ''"${a}"'') server.args;
        envLines = if server ? env then
          lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: ''${k} = "${v}"'') server.env)
        else "";
      in
      ''
        [mcp_servers.${name}]
        command = "${server.command}"
        args = [${argsStr}]
      '' + lib.optionalString (server ? env) ''

        [mcp_servers.${name}.env]
        ${envLines}
      '';

  mcpServersToml = lib.concatStringsSep "\n" (lib.mapAttrsToList mcpServerToToml mcpServers);

  # Base Codex config (TOML format)
  codexConfig = ''
    # Codex CLI configuration
    # Generated by Nix Home Manager

    # Model settings
    model = "gpt-5.2-codex"

    # MCP Servers
    ${mcpServersToml}
  '';

in
{
  # Create Codex config directory
  home.file.".codex/.keep".text = "";

  # Copy skills to ~/.codex/skills/
  home.activation.copyCodexSkills = lib.hm.dag.entryAfter ["writeBoundary"] ''
    mkdir -p $HOME/.codex/skills
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: path: ''
      rm -rf $HOME/.codex/skills/${name}
      cp -rL ${path} $HOME/.codex/skills/${name}
      chmod -R u+w $HOME/.codex/skills/${name}
    '') skillsToCopy)}
  '';

  # Copy agents to ~/.codex/agents/
  home.activation.copyCodexAgents = lib.hm.dag.entryAfter ["writeBoundary"] ''
    mkdir -p $HOME/.codex/agents
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: path: ''
      rm -f $HOME/.codex/agents/${name}.md
      cp -L ${path} $HOME/.codex/agents/${name}.md
      chmod u+w $HOME/.codex/agents/${name}.md
    '') agentsToCopy)}
  '';

  # Copy commands to ~/.codex/commands/
  home.activation.copyCodexCommands = lib.hm.dag.entryAfter ["writeBoundary"] ''
    mkdir -p $HOME/.codex/commands
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: path: ''
      rm -f $HOME/.codex/commands/${name}.md
      cp -L ${path} $HOME/.codex/commands/${name}.md
      chmod u+w $HOME/.codex/commands/${name}.md
    '') commandsToCopy)}
  '';

  # Generate Codex config.toml
  # Use activation script to merge/create (preserves user additions)
  home.activation.writeCodexConfig = lib.hm.dag.entryAfter ["writeBoundary"] ''
    CODEX_CONFIG="$HOME/.codex/config.toml"
    CODEX_DIR="$HOME/.codex"

    mkdir -p "$CODEX_DIR"

    # Write the MCP servers section
    # We use a marker to identify the managed section
    MANAGED_START="# --- BEGIN NIX-MANAGED MCP SERVERS ---"
    MANAGED_END="# --- END NIX-MANAGED MCP SERVERS ---"

    CONFIG_CONTENT='${codexConfig}'

    if [ -f "$CODEX_CONFIG" ]; then
      # Check if managed section exists
      if grep -q "$MANAGED_START" "$CODEX_CONFIG"; then
        # Replace existing managed section
        ${pkgs.gawk}/bin/awk -v start="$MANAGED_START" -v end="$MANAGED_END" -v content="$CONFIG_CONTENT" '
          BEGIN { in_managed=0; printed=0 }
          $0 ~ start { in_managed=1; print start; print content; printed=1; next }
          $0 ~ end { in_managed=0; print end; next }
          !in_managed { print }
        ' "$CODEX_CONFIG" > "$CODEX_CONFIG.tmp"
        mv "$CODEX_CONFIG.tmp" "$CODEX_CONFIG"
      else
        # Append managed section to existing file
        echo "" >> "$CODEX_CONFIG"
        echo "$MANAGED_START" >> "$CODEX_CONFIG"
        echo "$CONFIG_CONTENT" >> "$CODEX_CONFIG"
        echo "$MANAGED_END" >> "$CODEX_CONFIG"
      fi
    else
      # Create new file with managed section
      cat > "$CODEX_CONFIG" << 'NIXEOF'
# Codex CLI Configuration
# User settings go above the managed section

$MANAGED_START
$CONFIG_CONTENT
$MANAGED_END
NIXEOF
      # Replace variables (can't use heredoc variables directly)
      echo "# Codex CLI Configuration" > "$CODEX_CONFIG"
      echo "# User settings go above the managed section" >> "$CODEX_CONFIG"
      echo "" >> "$CODEX_CONFIG"
      echo "$MANAGED_START" >> "$CODEX_CONFIG"
      echo "$CONFIG_CONTENT" >> "$CODEX_CONFIG"
      echo "$MANAGED_END" >> "$CODEX_CONFIG"
    fi
  '';
}
