# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "k3s-server" do |server|


    server.vm.box = "generic/ubuntu2010"
    server.vm.network "public_network", ip: "192.168.1.200"
    server.vm.network "private_network", ip: "1.1.1.2"
    server.vm.hostname = "k3s-server"
    
    server.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y tmux vim
      su -l vagrant -c "wget https://raw.githubusercontent.com/atcol/config-files/master/tmux.conf -O ~/.tmux.conf"
      curl -sfL https://get.k3s.io | sh -
      k3s kubectl get node
    SHELL

  end

  config.vm.define "k3s-agent" do |server|


    server.vm.box = "generic/ubuntu2010"
    server.vm.network "public_network", ip: "192.168.1.201"
    server.vm.network "private_network", ip: "1.1.1.3"
    
    server.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y tmux vim
      su -l vagrant -c "wget https://raw.githubusercontent.com/atcol/config-files/master/tmux.conf -O ~/.tmux.conf"
      curl -sfL https://get.k3s.io | sh -
    SHELL

  end
end
